### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by nagyniki017** [PudingosLecso/coins-android#1]
SonarQube found:
- 4 bugs
- 1 vulnerability
- 54 code smells

**Comment by nagyniki017** [comment]
4 bugs fixed by better logging. It also solved the 1 existed vulnerability (caused by printStackTrace) and 1 code smell. (46e33243115510a8ae75b421f2787a8dcb770c68)
53 code smell remained.

**Comment by nagyniki017** [comment]
Simplifiyng type specification with <> operator to reduce the verbosity of generics code. (fae164286b84efc5c04cab70c1544fac7033bb76)

**Comment by nagyniki017** [comment]
Added private constructor to utility class which only contains static members. Java added implicit public constructor because the class did not define any explicitly. As a utility class shouldn't be instantiated, it can be prevented by explicit private constructor. (378f57b68674f27770c3aef57208ad9d531c3cd8)

**Comment by nagyniki017** [comment]
Use different name than "_" as in modern Java versions it's marked as an invalid identifier. (efb0501d6760db32982608e647697ac2a4356de0)

**Comment by nagyniki017** [comment]
Unneccesary switch structure replaced with if-then structure. (7716197a2e5d752056f78d0b806548252a6a443b)

**Comment by nagyniki017** [comment]
No issues left according to SonarQube. The other code smells appeared in generated files, which are not ment to be fixed.

**Comment by tothand95** [comment]
code review submited for the changes.

**Comment by nagyniki017** [comment]
Log messages are more specific what was suggested by the review. (08c0872a9b514d44091067b744b680cfbf6380c6 and 69e2021d74aab6f26239152c87178864a43ba2ed)

**Comment by tothand95** [comment]
issue solved
